spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: trip_core
    open-in-view: false

security:
  jwt:
    secret: ${JWT_ACCESS_SECRET}

hashids:
  salt: ${HASHIDS_SALT:6d8a1d503a90486cd6cef4fb216faabf}
  min-length: ${HASHIDS_MIN_LENGTH:8}

server:
  servlet:
    context-path: ${API_BASE_PATH:/api}
  port: 8081
