spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trip_budget?currentSchema=trip_core
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: travel
    open-in-view: false